### ISSUE TITLE
Strange behavior between GBC and SGB modes on Pokémon RB

### ISSUE THREAD

**Issue by Sirix1995** [Drenn1/GameYob#182]
Hi ! I noticed something strange on the emulator today !

As I know, Pokémon Red and Blue have three different graphics types : Game Boy graphics, with only grey scales, Game Boy Color graphics, with a green and red palette for Pokémon red and a blue and red palette for Pokémon Blue, and Super Game Boy graphics, which looks a little like Pokémon Yellow.

I have no problem for switching to GB classic graphics and SGB graphics. But, when I put the emulator to "Prefer GBC", the games still look in SGB graphics...Is it normal ?

**Comment by Drenn1** [comment]
Pokemon Red and Blue do not have GBC support. Rather, when booted on a GBC, the system itself applies some pre-programmed palettes to the games. (Use of the GBC bios is supported in GameYob so you can still achieve this effect. If the file is named "gbc_bios.bin" in your ROM folder then it should be detected automatically I think.)

Pokemon Yellow, on the other hand, does have native GBC support, which is why it works how you expect.
